
# Copyright 2019 Ciena Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

defaults:
  image_tag: master
  image_pullPolicy: Always

images:
  adapter_open_olt:
#    repository: "etowah/voltha-openolt-adapter"
#    tag_go: tptest
#    tag: test-py
    tag_go: master-go
#  adapter_open_onu:
#     repository: "https://hub.docker.com/r/etowah/voltha-openonu-adapter"
#     tag: "tptest"
  cli:
    repository: "etowah/voltha-cli"
    tag: "tptest"
  ofagent:
    repository: "etowah/voltha-ofagent"
    tag: "tptest"
  ro_core:
    repository: "etowah/voltha-ro-core"
    tag: "tptest"
  rw_core:
    repository: "smbaker/voltha-rw-core"
    tag: "test"
#    repository: "etowah/voltha-rw-core"
#    tag: "tptest"
#    repository: "karthick18/voltha-rw-core"
#    tag: "2.1.0-dev-dirty-tp-chan"
  afrouter:
    repository: "smbaker/voltha-afrouter"
    tag: "test"
#    repository: "etowah/voltha-afrouter"
#    tag: "tptest"
  afrouterd:
    repository: "smbaker/voltha-afrouterd"
    tag: "test"
#    repository: "etowah/voltha-afrouterd"
#    tag: "tptest"
  onos:
    tag: master
    repository: voltha/voltha-onos
#    tag: "1.13.9"
#    tag: "1.13.5"
  bbsim:
    repository: "smbaker/voltha-bbsim"
    tag: "14933"
#    repository: "etowah/voltha-bbsim"
#    tag: "tptest"

deployments:
  etcdOperator: true
  backupOperator: false
  restoreOperator: false

voltha-etcd-cluster:
  clusterSize: 1

onos_env:
- name: POD_IP
  valueFrom:
  fieldRef:
    fieldPath: status.podIP
- name: NAMESPACE
  valueFrom:
  fieldRef:
    fieldPath: metadata.namespace
- name: ONOS_APPS
  value: "drivers,openflow-base,hostprovider"

# Customization for BBSIM
kafka_broker: 'voltha-kafka.voltha.svc.cluster.local:9092'
pon_ports: 1
onus_per_pon_port: 1
